# Generated by Django 3.0.3 on 2020-02-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyqapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
