# Generated by Django 2.0.8 on 2020-03-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyqapp', '0003_ages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ages',
            name='scontend',
        ),
        migrations.RemoveField(
            model_name='ages',
            name='sgender',
        ),
        migrations.RemoveField(
            model_name='ages',
            name='sgrade',
        ),
    ]
